- src/sass/components/_movie-details.scss
Фон кнопок за замовчанням (сірий) виправлений на прозорий
> Виправлений фон неактивних кнопок подробиць фільму

- package-lock.json
- package.json
- src/index.js
- src/js/onQueueClick.js
Функція виведення зі сховища переліку фільмів з черги Queue, не прив'язана до кнопки, бо кнопка вісутня. Додатково підвантажились якісь зміни в package.json, тому що виконала npx browserslist@latest --update-db
> Створена функція виведення на екран фільмів з локального сховища черги

- src/sass/components/_movie-details.scss
- src/sass/components/_trending.scss
Зміни до trending.scss та movie-details.scss
> Зміна у css жирності заголовків фільмів на inherit від body

- src/sass/components/_movie-details.scss
- src/sass/components/_trending.scss
Зміна розміру шрифта заголовків фільмів відповідно до зауважень на нараді
> Наслідування розміру шрифта для назв фільмів

- src/sass/components/_header.scss
Виправив текст, який вибиває при неправильному введені запиту
> bugfix search text

- src/sass/components/_header.scss
Розтягнув фонові зображення в хедері на всю ширину екрану для Home і Library для десктопу
> bugfix background image

- src/js/addFilm.js
- src/js/deleteFilm.js
- src/js/fetchMovieById.js
- src/js/renderMovie.js
- src/js/renderMovieCard.js
Додавання до розмітки ідентифікатора фільму для виклику модалки та роботи з кнопками в ній. Доопрацювання роботи кнопок. Додавання функції пошуку фільму за ідентифікатором на випадок відсутності інформації про фільму у локальному сховищі (ключ сховища поточної галереї необхідно уніфікувати).
> Додавання до розмітки ідентифікатора фільму

- src/js/header-my-library.js
- src/sass/components/_header.scss
- src/sass/components/_my-library-btn.scss
Виправив текст "помилка" в разі введення некоректного запиту і також виправив логотип
> bugfix search text error and logo

- src/partials/header.html
> fixing loader html

- src/index.js
- src/js/keyWordMovieSearch.js
Поменял ключ для хранения фильмов в локальном хранилище с trending на currentFilms
Добавил сохраниения результата поиска фильмов в currentFilms
> add 'currentFilms'

- src/sass/components/_movie-details.scss
- src/sass/components/_trending.scss
Видалена властивість word-break: break-all;
> Видалена властивість розриву слів

- src/js/addFilm.js
- src/js/deleteFilm.js
- src/js/libraryButton.js
Коректне виведення інформації у консоль про порожню бібліотеку.
> Виправлення лапок для виведення інформації у консоль

- src/index.js
- src/js/addDataToLocalStorage.js
- src/js/get-refs.js
- src/js/keyWordMovieSearch.js
добавл в рефы ключь для хранения фильмов
movieKey: 'currentFilms',
+ дописал функцию для сохранения инфо в локальное хранилище
addDataToLocalStorage
> add function

- src/js/get-refs.js
- src/js/renderMovieCard.js
- src/js/renderTrending.js
Редагування функції renderTrending для врахування відкриття бібліотеки. Додавання посилання на кнопки бібліотеки до get-refs.
> Виведення рейтингу фільмів у бібліотеці

- src/js/keyWordMovieSearch.js
-fixed errorNotification
-add trim()
> some bud fix

- src/index.html
- src/js/get-refs.js
- src/js/openCard.js
- src/js/renderMovie.js
- src/js/renderMovieCard.js
- src/partials/gallery.html
открытие модалки при клике на карточку фильма не готово полностью
Реализовано:
1. При клике на катрочку в любом месте срабатывает функция openCard которая считывает id фильма, находит в хранилище по іd объект этого фильма и записывает его в переменную film.
Далее пока-что не знаю:
1. как правильно передать film в функцию renderMovie , так-как эта функция принимает 3 параметра.
2. Не получается отобразить модалку (даже пустую) ошибка Cannot read properties of null на insertAdjacentHTML.
3.Вообщем, есть много вопросов по этому заданию
> открытие модалки

- src/index.js
- src/js/fetchPopularMovies.js
- src/js/onLoaderHidden.js
- src/js/onLoaderVisible.js
- src/partials/header.html
- src/sass/components/_loader.scss
Добавил спинер при первой загрузке страницы.
Изменил внешний вид+расположение
> add some changes

- src/index.js
- src/js/addFilm.js
- src/js/addTestWatchedQueue.js
- src/js/deleteFilm.js
- src/js/fetchGenres.js
- src/js/libraryButton.js
- src/js/renderMovie.js
- src/js/renderMovieCard.js
- src/js/renderTrending.js
Усунення потреби в передачі жанрів до фукнції renderTrending
> Доопрацювання функції відмальовування карток фільмів

- src/js/header-my-library.js
додавання класу visually-hidden до пагінації при натисканні кнопки My Library
> У бібліотеці пагінація прихована

- src/js/get-refs.js
- src/js/header-my-library.js
- src/sass/components/_header.scss
Підправив рефи і також підправив хедер
> bugfix header and corrected refs

- src/sass/components/_header.scss
Поставив плавний перехід на хедер
> feature transition in header

- src/js/renderMovie.js
- src/js/renderMovieCard.js
- src/sass/components/_movie-details.scss
Додавання hover для кнопок додавання/видалення фільмів з бібліотеки, додавання loading="lazy" до постерів фільмів, виведення на модалку популярності фільму з одним десятковим знаком.
> Доопрацювання стилів та розмітки карток фільмів

- src/js/renderMainPage.js
- src/sass/components/_header.scss
- src/sass/utils/_variables.scss
Если правильно понял, ховер с логотипа снимался мгновенно- это поправил, добавил transition
> add transition

- src/js/addFilm.js
Виправлений пошук фільму у локальному сховищі поточних фільмів. Видалене виведення у галарею сховища бібліотеки.
> Доопрацювання функції додавання фільму до бібліотеки

- src/js/renderMovieCard.js
добавляет рейтинг в карточку фильмов, при стартовой загрузке
> add movie vote

- src/js/keyWordMovieSearch.js
- src/js/pagination.js
- src/js/renderMovieCard.js
- src/js/renderTrending.js
Очищення класу visually-hidden у картки фільму, відповідне редагування фукнції renderTrending, очищення фукнцій інших учасників від жанрів при використання функції renderTrending
> Очищення фукнцій renderTrending та renderMovieCard

- src/js/get-refs.js
- src/js/pagination.js
- src/js/renderMainPage.js
- src/partials/gallery.html
- src/sass/components/_pagination.scss
fixed the btns order and hide first and last btns for first and last three pages.
> fixed pagination

- src/js/api.js
Копіювання усіх запитів до сервера до одного файлу для майбутньої оптимізації. Додавання запитів популярних, рейтингових, очікуваних, схожих та відеороликів.
> Розробка API-служби запитів до themoviedb.org

- src/js/modalLibraryButtons.js
Виправлення назви кнопки з Add from queue на Add to queue
> Виправлення назви кнопки додавання фільму до черги

- src/index.js
- src/js/openModalFilm.js
- src/js/pagination.js
Доопрацьована модалка (внесені тімлідом зміни перенесені після перевірки на натискання за межами картки). Пропозиція підключати css головної та паганації у файлі index.js
> Доопрацювання модалки на випадок натискання поза карткою галереї

- src/js/libraryButton.js
- src/js/renderMovieCard.js
- src/sass/components/_movie-details.scss
- src/sass/components/_trending.scss
Відновлення розмітки картки фільму на головній сторінці, організація позиціонування рейнгу через додатковий клас
> Відновлення розмітки картки, виконання рейтингу

- src/sass/components/_movie-details.scss
Повторне видалення стилів css для позиціонування рейтингу
> Видалення зайвих стилів

- src/js/footer-modal.js
- src/js/openModalFilm.js
добавил закрытие модального окна при клике на бэкдроп
> close modal

- src/js/renderMovieCard.js
Виправлення підпису картки N/A на Year Not Available
> Допис Year Not Available

- src/sass/components/_trending.scss
Додавання білого фону логотипу MovieDB для світлої теми та чорного для темної
> Зміна фону логотипу MovieDB картки фільму

- src/sass/base/_container.scss
- src/sass/components/_btn-change-theme.scss
Подвинул кнопку переключения темы внуть контейнера, для этого добавил контейнеру position: relative - в основной разметке вроде ничего не поломалось
> fix theme btn position

- src/js/addFilm.js
- src/js/modalLibraryButtons.js
- src/js/openModalFilm.js
- src/sass/components/_filter-btn.scss
- src/sass/components/_footer.scss
Доопрацювала кнопки модалки (фільми додавались тільки із сховища поточних, не враховуючи бібліотеку). Видалено подвоєння функцій для кнопок різних бібліотек (назва бібліотеки береться з назви кнопки). Видалений синій колір серця футера та закоментований синій колір кнопок day/week.
> Доопрацьована логіка додавання фільмів

- src/js/renderMainPage.js
- src/js/renderMainPageWeek.js
- src/js/sortMovies.js
Відновлення роботи кнопок сортування головної сторінки за фільмами, що знаходяться у тренді протягом дня або тижня
> Відновлення роботи сортування

- src/sass/base/_container.scss
- src/sass/components/_btn-change-theme.scss
- src/sass/components/_sidebar.scss
> fixed header dark mode and side bar

- src/js/api.js
- src/js/keyWordMovieSearch.js
- src/js/pagination.js
- src/js/renderMainPage.js
- src/partials/gallery.html
- src/sass/components/_filter-btn.scss
- added pagination to new filter buttons
- fixed bug when the wrong movie name entered
- deleted "popular" filter btn (agreed with Liliia)
> add pagination to new filter btn

- src/js/header-my-library.js
Доопрацювання стилів кнопок бібліотеки після зміни логіки відкриття головної сторінки
> Виправлення активної кнопки бібліотеки

- src/js/keyWordMovieSearch.js
Якщо вибрати інший фільтр і виконати пошук - фільтр не повертався у положення Today.
> Очищення фільтру під час пошуку

- src/index.js
- src/js/header-my-library.js
- src/js/keyWordMovieSearch.js
На вимогу Вікторії після виконання пошуку і виведення результатів з фільтрів знімається активна кнопка.
> Знято активну кнопку фільтра при виведенні результатів пошуку
